target("demo.explorer")
    add_rules("winui3.app")
    set_values("winui3.namespace", "explorer")
    add_rules("demo.common")
    add_includedirs("src")
    add_files("src/**.cpp", "src/**.idl", "src/**.xaml")
