-- WebView2 Hello World WinUI3 demo
target("demo.webview")
    add_rules("winui3.app")
    set_values("winui3.namespace", "webview")
    add_rules("demo.common")
    add_includedirs("src")
    add_rules("webview", {dist_dir = path.join(os.scriptdir(), "src", "web")})
    add_files("src/**.cpp")
    add_files("src/**.idl")
    add_files("src/**.xaml")
