target("demo.kanban")
    add_rules("winui3.app")
    set_values("winui3.namespace", "kanban")
    add_rules("demo.common")
    add_deps("demo.utils")
    add_includedirs("src")
    add_files("src/**.cpp", "src/**.idl", "src/**.xaml")
